[package]
name = "server"
version = "1.0.0-dev"
authors = ["buttercrab <jaeyong0201@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mighty = { path = "../mighty", default-features = false, features = ["server"] }

actix-web = "3"
actix-identity = "0.3"
clap = "3.0.0-beta.2"
rand = "0.7"
slog = "2.5"
slog-term = "2.6"
slog-async = "2.5"
slog-scope = "4.3"
slog-stdlog = "4.1"