[package]
name = "server"
version = "1.0.0-dev"
authors = ["buttercrab <jaeyong0201@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mighty = { path = "../mighty", default-features = false, features = ["server"] }

actix-identity = "0.3"
actix-web = "3"
clap = "3.0.0-beta.2"
handlebars = "3.5"
ignore = "0.4"
log = "0.4"
rand = "0.7"
serde_json = "1.0"
slog = "2.5"
slog-term = "2.6"
slog-async = "2.5"
slog-scope = "4.3"
slog-stdlog = "4.1"
walkdir = "2"

notify = { version = "4.0.15", optional = true }

[features]
default = []
watch-file = ["notify"]