[package]
name = "server"
version = "1.0.0-dev"
authors = ["buttercrab <jaeyong0201@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
core = { path = "../core", default-features = false, features = ["server"] }
actix-web = "2"
actix-rt = "1"
clap = { git = "https://github.com/clap-rs/clap/" }
