name: build
on: [ push, pull_requests ]

jobs:
  ci:
    name: Test
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        build: [ stable, beta, nightly, macos, windows, msrv ]
        include:
          - build: stable
            os: ubuntu-latest
            rust: stable
          - build: beta
            os: ubuntu-latest
            rust: beta
          - build: nightly
            os: ubuntu-latest
            rust: nightly
          - build: macos
            os: macos-latest
            rust: stable

    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true
          components: rustfmt

      - uses: actions-rs/cargo@v1
        with:
          command: build

      - uses: actions-rs/cargo@v1
        with:
          command: test

      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

      - name: testing wasm
        run: |
          if [ -f "${HOME}/.cargo/bin/wasm-pack" ]; then
            rm ${HOME}/.cargo/bin/wasm-pack
          fi
          curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
          wasm-pack test --node --firefox --chrome --safari --headless
