name: clippy
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  ci:
    name: clippy
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        build: [ stable, beta, nightly, macos ]

        include:
          - build: stable
            os: ubuntu-latest
            rust: stable

          - build: beta
            os: ubuntu-latest
            rust: beta

          - build: nightly
            os: ubuntu-latest
            rust: nightly

          - build: macos
            os: macos-latest
            rust: stable

    steps:
      - uses: actions/checkout@v2

      - name: Setting up rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true
          components: clippy

      - name: Checking if it builds without warnings - config (default feature)
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --all-targets --manifest-path config/Cargo.toml -- -D warnings

      - name: Checking if it builds without warnings - mighty (default feature)
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --all-targets --manifest-path mighty/Cargo.toml -- -D warnings

      - name: Checking if it builds without warnings - mighty (server feature)
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --all-targets --manifest-path mighty/Cargo.toml --features server -- -D warnings

      - name: Checking if it builds without warnings - mighty (client feature)
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --all-targets --manifest-path mighty/Cargo.toml --features client -- -D warnings

      - name: Checking if it builds without warnings - client (default feature)
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --all-targets --manifest-path client/Cargo.toml -- -D warnings

      - name: Checking if it builds without warnings - server (default feature)
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --all-targets --manifest-path server/Cargo.toml -- -D warnings

      - name: Checking if it builds without warnings - server (watch-file feature)
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --all-targets --manifest-path server/Cargo.toml --features watch-file -- -D warnings

      - name: Checking if it builds without warnings - types (default feature)
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --all-targets --manifest-path types/Cargo.toml -- -D warnings

      - name: Checking if it builds without warnings - types (server feature)
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --all-targets --manifest-path types/Cargo.toml --features server -- -D warnings
