name: test
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  ci:
    name: test
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        build: [ stable, beta, nightly, macos ]

        include:
          - build: stable
            os: ubuntu-latest
            rust: stable
            browsers: --node --firefox --chrome

          - build: beta
            os: ubuntu-latest
            rust: beta
            browsers: --node --firefox --chrome

          - build: nightly
            os: ubuntu-latest
            rust: nightly
            browsers: --node --firefox --chrome

          - build: macos
            os: macos-latest
            rust: stable
            browsers: --node --firefox --chrome --safari

    steps:
      - uses: actions/checkout@v2

      - name: Setting up rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true

      - name: Checking if it builds without errors - config (default feature)
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --manifest-path config/Cargo.toml

      - name: Checking if it builds without errors - mighty (default feature)
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --manifest-path mighty/Cargo.toml

      - name: Checking if it builds without errors - mighty (server feature)
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --manifest-path mighty/Cargo.toml --features server

      - name: Checking if it builds without errors - mighty (client feature)
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --manifest-path mighty/Cargo.toml --features client

      - name: Checking if it builds without errors - client (default feature)
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --manifest-path client/Cargo.toml

      - name: Checking if it builds without errors - server (default feature)
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --manifest-path server/Cargo.toml

      - name: Checking if it builds without errors - server (watch-file feature)
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --manifest-path server/Cargo.toml --features watch-file

      - name: Checking if it builds without errors - types (default feature)
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --manifest-path types/Cargo.toml

      - name: Checking if it builds without errors - types (server feature)
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --manifest-path types/Cargo.toml --features server
